name: SadTalker Inference (CPU)

on:
  workflow_dispatch:

jobs:
  run-inference:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v4

    - name: Clone SadTalker repository
      run: |
        git clone https://github.com/OpenTalker/SadTalker.git
        cd SadTalker
        git checkout main

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y ffmpeg libgl1 wget unzip

    - name: Set up Python environment and install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install torch==1.12.1+cpu torchvision==0.13.1+cpu torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cpu
        pip install -r SadTalker/requirements.txt

    - name: Download pretrained models (v0.0.2-rc)
      run: |
        mkdir -p checkpoints
        cd checkpoints
    
        wget https://github.com/OpenTalker/SadTalker/releases/download/v0.0.2-rc/SadTalker_V0.0.2_256.safetensors
        wget https://github.com/OpenTalker/SadTalker/releases/download/v0.0.2-rc/SadTalker_V0.0.2_512.safetensors
    
        wget https://github.com/OpenTalker/SadTalker/releases/download/v0.0.2-rc/mapping_00229-model.pth.tar
    
        cd ..
    - name: Extract first frame from video as source image
      run: |
        mkdir -p extracted
        ffmpeg -i "Brooke Studio 0621.mp4" -vf "select=eq(n\,0)" -q:v 3 extracted/source.png

    - name: Run inference
      run: |
        source venv/bin/activate
        python SadTalker/inference.py \
          --driven_audio "voice.mp3" \
          --source_image extracted/source.png \
          --result_dir output \
          --cpu

    - name: Upload output artifact
      uses: actions/upload-artifact@v4
      with:
        name: sadtalker-output
        path: output
